roboptim::OptimizationLogger< T > Class Template Reference
roboptim::OptimizationLogger< T > Class Template Reference
#include <roboptim/core/optimization-logger.hh>
Public Types
typedef T solver_t
typedef solver_t::problem_t problem_t
typedef
solver_t::problem_t::value_type value_type
typedef
solver_t::problem_t::vector_t vector_t
typedef
solver_t::problem_t::function_t::jacobian_t jacobian_t
Public Member Functions
OptimizationLogger (solver_t &solver, const boost::filesystem::path &path)
virtual ~OptimizationLogger ()
Protected Member Functions
void perIterationCallback (const typename solver_t::vector_t &x, const typename solver_t::problem_t &pb)
virtual void perIterationCallbackUnsafe (const typename solver_t::vector_t &x, const typename solver_t::problem_t &pb)
const solver_t & solver () const throw ()
solver_t & solver () throw ()
boost::filesystem::path & path () const throw ()
boost::filesystem::path & path () throw ()
unsigned callbackCallId () const throw ()
template<typename T>
class roboptim::OptimizationLogger< T >
Member Typedef Documentation
template<typename T > typedef solver_t::problem_t::function_t::jacobian_t roboptim::OptimizationLogger< T >::jacobian_t
template<typename T > typedef solver_t::problem_t roboptim::OptimizationLogger< T >::problem_t
template<typename T > typedef T roboptim::OptimizationLogger< T >::solver_t
template<typename T > typedef solver_t::problem_t::value_type roboptim::OptimizationLogger< T >::value_type
template<typename T > typedef solver_t::problem_t::vector_t roboptim::OptimizationLogger< T >::vector_t
Constructor & Destructor Documentation
template<typename T > roboptim::OptimizationLogger< T >::OptimizationLogger (solver_t & solver, const boost::filesystem::path & path) [inline, explicit]
References roboptim::iendl().
template<typename T > virtual roboptim::OptimizationLogger< T >::~OptimizationLogger () [inline, virtual]
References roboptim::iendl().
Member Function Documentation
template<typename T > unsigned roboptim::OptimizationLogger< T >::callbackCallId () const throw () [inline, protected]
template<typename T > boost::filesystem::path& roboptim::OptimizationLogger< T >::path () const throw () [inline, protected]
template<typename T > boost::filesystem::path& roboptim::OptimizationLogger< T >::path () throw () [inline, protected]
template<typename T > void roboptim::OptimizationLogger< T >::perIterationCallback (const typename solver_t::vector_t & x, const typename solver_t::problem_t & pb) [inline, protected]
References roboptim::OptimizationLogger< T >::perIterationCallbackUnsafe().
template<typename T > virtual void roboptim::OptimizationLogger< T >::perIterationCallbackUnsafe (const typename solver_t::vector_t & x, const typename solver_t::problem_t & pb) [inline, protected, virtual]
References roboptim::Problem< F, CLIST >::constraints(), roboptim::decindent(), roboptim::Problem< F, CLIST >::function(), roboptim::iendl(), and roboptim::incindent().
Referenced by roboptim::OptimizationLogger< T >::perIterationCallback().
template<typename T > const solver_t& roboptim::OptimizationLogger< T >::solver () const throw () [inline, protected]
template<typename T > solver_t& roboptim::OptimizationLogger< T >::solver () throw () [inline, protected]