roboptim::TwiceDifferentiableFunction Class Reference
roboptim::TwiceDifferentiableFunction Class Reference
Mathematical abstract functions
Define an abstract function which is derivable twice ().
#include <roboptim/core/twice-differentiable-function.hh>
Public Types
typedef matrix_t hessian_t
Hessian type.
typedef std::pair< size_type,
size_type > hessianSize_t
Hessian size type represented as a pair of values.
Public Member Functions
hessianSize_t hessianSize () const throw ()
Return the size of a hessian.
bool isValidHessian (const hessian_t &hessian) const throw ()
Check if the hessian is valid (check sizes).
hessian_t hessian (const argument_t &argument, size_type functionId=0) const throw ()
Compute the hessian at a given point.
void hessian (hessian_t &hessian, const argument_t &argument, size_type functionId=0) const throw ()
Compute the hessian at a given point.
virtual std::ostream & print (std::ostream &) const throw ()
Display the function on the specified output stream.
Protected Member Functions
TwiceDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string()) throw ()
Concrete class constructor should call this constructor.
virtual void impl_hessian (hessian_t &hessian, const argument_t &argument, size_type functionId=0) const =0 throw ()
Hessian evaluation.
void setZero (hessian_t &symmetric) const
Set a symmetric matrix to zero.
Detailed Description
Define an abstract function which is derivable twice ().
A twice derivable function is a derivable function which provides a way to compute its hessian.
, where is the input size and is the output size.
Hessian computation is done through the impl_hessian method that has to implemented by the concrete class inheriting this class.
The hessian of a function where and is a tensor. To avoid this costly representation, the function is split into functions. See #DifferentialeFunction documentation for more information.
Member Typedef Documentation
typedef matrix_t roboptim::TwiceDifferentiableFunction::hessian_t
Hessian type.
Hessians are symmetric matrices.
typedef std::pair<size_type, size_type> roboptim::TwiceDifferentiableFunction::hessianSize_t
Hessian size type represented as a pair of values.
Constructor & Destructor Documentation
roboptim::TwiceDifferentiableFunction::TwiceDifferentiableFunction (size_type inputSize, size_type outputSize = 1, std::string name = std::string ()) throw () [protected]
Concrete class constructor should call this constructor.
Parameters:
inputSize input size (argument size)
outputSize output size (result size)
name function's name
Member Function Documentation
hessian_t roboptim::TwiceDifferentiableFunction::hessian (const argument_t & argument, size_type functionId = 0) const throw () [inline]
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters:
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Returns:
computed hessian
Examples:
numeric-quadratic-function.cc.
void roboptim::TwiceDifferentiableFunction::hessian (hessian_t & hessian, const argument_t & argument, size_type functionId = 0) const throw () [inline]
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters:
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
hessianSize_t roboptim::TwiceDifferentiableFunction::hessianSize () const throw () [inline]
Return the size of a hessian.
Hessian size is equales to (input size, input size).
Returns:
hessian's size as a pair
virtual void roboptim::TwiceDifferentiableFunction::impl_hessian (hessian_t & hessian, const argument_t & argument, size_type functionId = 0) const throw () [protected, pure virtual]
Hessian evaluation.
Compute the hessian, has to be implemented in concrete classes. The hessian is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call hessian instead.
Parameters:
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Implemented in roboptim::NTimesDerivableFunction< 2 >, and roboptim::LinearFunction.
bool roboptim::TwiceDifferentiableFunction::isValidHessian (const hessian_t & hessian) const throw () [inline]
Check if the hessian is valid (check sizes).
Parameters:
hessian hessian that will be checked
Returns:
true if valid, false if not
std::ostream & roboptim::TwiceDifferentiableFunction::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::DifferentiableFunction.
Reimplemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::NumericQuadraticFunction, roboptim::LinearFunction, roboptim::NumericLinearFunction, roboptim::QuadraticFunction, roboptim::IdentityFunction, and roboptim::ConstantFunction.
void roboptim::TwiceDifferentiableFunction::setZero (hessian_t & symmetric) const [inline, protected]
Set a symmetric matrix to zero.
Note:
there might be an eigen function to do that.
References setZero().
Referenced by roboptim::LinearFunction::impl_hessian(), and setZero().