roboptim::BadGradient Class Reference
roboptim::BadGradient Class Reference
Exception thrown when a gradient check fail.
#include <roboptim/core/finite-difference-gradient.hh>
Public Types
typedef
DifferentiableFunction::vector_t vector_t
Import vector.
typedef
DifferentiableFunction::gradient_t gradient_t
Import gradient.
typedef
DifferentiableFunction::value_type value_type
Import value_type.
typedef
DifferentiableFunction::size_type size_type
Import size_type.
Public Member Functions
BadGradient (const vector_t &x, const gradient_t &analyticalGradient, const gradient_t &finiteDifferenceGradient, const value_type &threshold)
Default constructor.
virtual ~BadGradient () throw ()
virtual std::ostream & print (std::ostream &o) const throw ()
Display the exception on the specified output stream.
Public Attributes
vector_t x_
Gradient has been computed for this point.
gradient_t analyticalGradient_
Analytical gradient.
gradient_t finiteDifferenceGradient_
Gradient computed through finite differences.
value_type maxDelta_
Maximum error.
size_type maxDeltaComponent_
Component containing the maximum error.
value_type threshold_
Allowed threshold.
Detailed Description
Exception thrown when a gradient check fail.
Member Typedef Documentation
typedef DifferentiableFunction::gradient_t roboptim::BadGradient::gradient_t
Import gradient.
typedef DifferentiableFunction::size_type roboptim::BadGradient::size_type
Import size_type.
typedef DifferentiableFunction::value_type roboptim::BadGradient::value_type
Import value_type.
typedef DifferentiableFunction::vector_t roboptim::BadGradient::vector_t
Import vector.
Constructor & Destructor Documentation
roboptim::BadGradient::BadGradient (const vector_t & x, const gradient_t & analyticalGradient, const gradient_t & finiteDifferenceGradient, const value_type & threshold)
Default constructor.
References maxDelta_, and maxDeltaComponent_.
roboptim::BadGradient::~BadGradient () throw () [virtual]
Member Function Documentation
std::ostream & roboptim::BadGradient::print (std::ostream & o) const throw () [virtual]
Display the exception on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
Referenced by roboptim::operator<<().
Member Data Documentation
gradient_t roboptim::BadGradient::analyticalGradient_
Analytical gradient.
gradient_t roboptim::BadGradient::finiteDifferenceGradient_
Gradient computed through finite differences.
value_type roboptim::BadGradient::maxDelta_
Maximum error.
Referenced by BadGradient().
size_type roboptim::BadGradient::maxDeltaComponent_
Component containing the maximum error.
Referenced by BadGradient().
value_type roboptim::BadGradient::threshold_
Allowed threshold.
vector_t roboptim::BadGradient::x_
Gradient has been computed for this point.