roboptim::DifferentiableFunction Class Reference
roboptim::DifferentiableFunction Class Reference
Mathematical abstract functions
Define an abstract derivable function ().
#include <roboptim/core/differentiable-function.hh>
Public Types
typedef Function::vector_t vector_t
Basic vector type.
typedef Function::matrix_t matrix_t
Basic matrix type.
typedef vector_t gradient_t
Gradient type.
typedef matrix_t jacobian_t
Jacobian type.
typedef std::pair< size_type,
size_type > jacobianSize_t
Jacobian size type (pair of values).
Public Member Functions
size_type gradientSize () const throw ()
Return the gradient size.
jacobianSize_t jacobianSize () const throw ()
Return the jacobian size as a pair.
bool isValidGradient (const gradient_t &gradient) const throw ()
Check if the gradient is valid (check size).
bool isValidJacobian (const jacobian_t &jacobian) const throw ()
Check if the jacobian is valid (check sizes).
jacobian_t jacobian (const argument_t &argument) const throw ()
Computes the jacobian.
void jacobian (jacobian_t &jacobian, const argument_t &argument) const throw ()
Computes the jacobian.
gradient_t gradient (const argument_t &argument, size_type functionId=0) const throw ()
Computes the gradient.
void gradient (gradient_t &gradient, const argument_t &argument, size_type functionId=0) const throw ()
Computes the gradient.
virtual std::ostream & print (std::ostream &o) const throw ()
Display the function on the specified output stream.
Protected Member Functions
DifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string()) throw ()
Concrete class constructor should call this constructor.
virtual void impl_jacobian (jacobian_t &jacobian, const argument_t &arg) const throw ()
Jacobian evaluation.
virtual void impl_gradient (gradient_t &gradient, const argument_t &argument, size_type functionId=0) const =0 throw ()
Gradient evaluation.
Detailed Description
Define an abstract derivable function ().
A derivable function which provides a way to compute its gradient/jacobian.
, where is the input size and is the output size.
Gradient computation is done through the impl_gradient method that has to implemented by the concrete class inheriting this class.
Jacobian computation is automatically done by concatenating gradients together, however this naive implementation can be overridden by the concrete class.
The gradient of a function where and is a matrix. As this representation is costly, RobOptim considers these functions as functions. Through that mechanism, gradients are always vectors and jacobian are always matrices. When the gradient or the jacobian has to be computed, one has to precise which of the functions should be considered.
If , then the function id must always be 0 and can be safely ignored in the gradient/jacobian computation. The class provides a default value for the function id so that these functions do not have to explicitly set the function id.
Examples:
finite-difference-gradient.cc, and problem-cc.cc.
Member Typedef Documentation
typedef vector_t roboptim::DifferentiableFunction::gradient_t
Gradient type.
Reimplemented in roboptim::SumOfC1Squares.
typedef matrix_t roboptim::DifferentiableFunction::jacobian_t
Jacobian type.
Reimplemented in roboptim::SumOfC1Squares.
typedef std::pair<size_type, size_type> roboptim::DifferentiableFunction::jacobianSize_t
Jacobian size type (pair of values).
Reimplemented in roboptim::SumOfC1Squares.
typedef Function::matrix_t roboptim::DifferentiableFunction::matrix_t
Basic matrix type.
This basic matrix type is used each time a two dimensional matrix of values is needed.
Attention:
It is good practice in RobOptim to rely on this type when a matrix of values is needed instead of relying on a particular implementation.
Reimplemented from roboptim::GenericFunction< T >.
Examples:
numeric-linear-function.cc, and numeric-quadratic-function.cc.
typedef Function::vector_t roboptim::DifferentiableFunction::vector_t
Basic vector type.
This basic vector type is used each time a vector of values is required.
Attention:
It is good practice in RobOptim to rely on this type when a vector of values is needed instead of relying on a particular implementation.
Reimplemented from roboptim::GenericFunction< T >.
Examples:
constant-function.cc, identity-function.cc, numeric-linear-function.cc, numeric-quadratic-function.cc, and problem-cc.cc.
Constructor & Destructor Documentation
roboptim::DifferentiableFunction::DifferentiableFunction (size_type inputSize, size_type outputSize = 1, std::string name = std::string ()) throw () [protected]
Concrete class constructor should call this constructor.
Parameters:
inputSize input size (argument size)
outputSize output size (result size)
name function's name
Member Function Documentation
gradient_t roboptim::DifferentiableFunction::gradient (const argument_t & argument, size_type functionId = 0) const throw () [inline]
Computes the gradient.
Parameters:
argument point at which the gradient will be computed
functionId function id in split representation
Returns:
gradient vector
Examples:
constant-function.cc, identity-function.cc, and numeric-quadratic-function.cc.
Referenced by roboptim::checkGradient(), and roboptim::checkGradientAndThrow().
void roboptim::DifferentiableFunction::gradient (gradient_t & gradient, const argument_t & argument, size_type functionId = 0) const throw () [inline]
Computes the gradient.
Program will abort if the gradient size is wrong before or after the gradient computation.
Parameters:
gradient gradient will be stored in this argument
argument point at which the gradient will be computed
functionId function id in split representation
Returns:
gradient vector
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
size_type roboptim::DifferentiableFunction::gradientSize () const throw () [inline]
Return the gradient size.
Gradient size is equals to the input size.
virtual void roboptim::DifferentiableFunction::impl_gradient (gradient_t & gradient, const argument_t & argument, size_type functionId = 0) const throw () [protected, pure virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::FiniteDifferenceGradient< FdgPolicy >, roboptim::SumOfC1Squares, and roboptim::ConstantFunction.
void roboptim::DifferentiableFunction::impl_jacobian (jacobian_t & jacobian, const argument_t & arg) const throw () [protected, virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Reimplemented in roboptim::IdentityFunction, and roboptim::ConstantFunction.
bool roboptim::DifferentiableFunction::isValidGradient (const gradient_t & gradient) const throw () [inline]
Check if the gradient is valid (check size).
Parameters:
gradient checked gradient
Returns:
true if valid, false if not
bool roboptim::DifferentiableFunction::isValidJacobian (const jacobian_t & jacobian) const throw () [inline]
Check if the jacobian is valid (check sizes).
Parameters:
jacobian checked jacobian
Returns:
true if valid, false if not
jacobian_t roboptim::DifferentiableFunction::jacobian (const argument_t & argument) const throw () [inline]
Computes the jacobian.
Parameters:
argument point at which the jacobian will be computed
Returns:
jacobian matrix
Examples:
constant-function.cc, numeric-linear-function.cc, and numeric-quadratic-function.cc.
void roboptim::DifferentiableFunction::jacobian (jacobian_t & jacobian, const argument_t & argument) const throw () [inline]
Computes the jacobian.
Program will abort if the jacobian size is wrong before or after the jacobian computation.
Parameters:
jacobian jacobian will be stored in this argument
argument point at which the jacobian will be computed
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
jacobianSize_t roboptim::DifferentiableFunction::jacobianSize () const throw () [inline]
Return the jacobian size as a pair.
Gradient size is equals to (output size, input size).
Referenced by roboptim::IdentityFunction::impl_jacobian().
std::ostream & roboptim::DifferentiableFunction::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericFunction< T >.
Reimplemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::TwiceDifferentiableFunction, roboptim::NumericQuadraticFunction, roboptim::LinearFunction, roboptim::NumericLinearFunction, roboptim::QuadraticFunction, roboptim::IdentityFunction, and roboptim::ConstantFunction.