roboptim Namespace Reference
roboptim Namespace Reference
Meta-functions, functions and solvers related classes.
Namespaces
namespace detail
namespace fg
namespace finiteDifferenceGradientPolicies
Contains finite difference gradients policies.
namespace visualization
Graphic visualization.
Classes
class DerivableParametrizedFunction
Parametrized function with parameter derivative available.
struct derivativeSize< GenericFunction< T > >
struct derivativeSize< GenericDifferentiableFunction< T > >
struct derivativeSize< GenericTwiceDifferentiableFunction< T > >
struct derivativeSize< NTimesDerivableFunction< N > >
class GenericDifferentiableFunction
Define an abstract derivable function ().
class CachedFunction
Store previous function computation.
class Chain
Chain two RobOptim functions.
class Concatenate
Concatenate several functions output.
class Derivative
class Map
Apply a function several times to an input vector.
class Minus
Substract two RobOptim functions.
class Plus
Sum two RobOptim functions.
class Product
Product of two RobOptim functions.
class Scalar
Select part of a function.
class Selection
Select part of a function.
class Split
class BadGradient
Exception thrown when a gradient check fails.
class BadJacobian
Exception thrown when a Jacobian check fails.
class GenericFiniteDifferenceGradient
Compute automatically a gradient with finite differences.
class GenericConstantFunction
Constant function.
class Cos
Cos function.
class GenericIdentityFunction
Identity function.
class Sin
Sin function.
struct GenericFunctionTraits
GenericFunction traits.
class GenericFunction
Define an abstract mathematical function ().
struct GenericFunctionTraits< EigenMatrixDense >
Trait specializing GenericFunction for Eigen dense matrices.
struct GenericFunctionTraits< EigenMatrixSparse >
Trait specializing GenericFunction for Eigen sparse matrices.
class NoSolution
Tag a result if no solution has been found.
struct EigenMatrixDense
Tag type for functions using Eigen dense matrices.
struct EigenMatrixSparse
Tag type for functions using Eigen sparse matrices.
class GenericSolver
Abstract interface satisfied by all solvers.
class GenericLinearFunction
Define an abstract linear function.
class NTimesDerivableFunction< 2 >
Explicit specialization for the stop case of NTimesDerivable class.
class NTimesDerivableFunction
Define a function, derivable n times ().
class GenericNumericLinearFunction
Build a linear function from a vector and a matrix.
class GenericNumericQuadraticFunction
Build a quadratic function from a matrix and a vector.
class OptimizationLogger
class ParametrizedFunction
Define an abstract parametrized mathematical function ().
class DummySolverLastState
Dummy solver which always fails, but returns the last state of the solver.
class DummySolver
Dummy solver which always fails.
class Problem< F, boost::mpl::vector<> >
class Problem
class GenericQuadraticFunction
Define an abstract quadratic function.
class ResultWithWarnings
Represents the solution of an optimization problem when errors occurred during the solving process.
class Result
Represents the solution of an optimization problem.
class SolverError
Base exception class for solving errors.
class SolverFactory
Define a solver factory that instanciate the plug-ins.
class SolverWarning
Exception used for non-critical errors during optimization.
struct Parameter
Parameters type.
class Solver
Solver for a specific problem class.
class SumOfC1Squares
Sum of the squares of differentiable functions.
class GenericTwiceDifferentiableFunction
Define an abstract function which is derivable twice ().
Typedefs
typedef DifferentiableFunction DerivableFunction
Legacy name of TwiceDifferentiableFunction.
typedef
DifferentiableSparseFunction DerivableSparseFunction
Legacy name of TwiceDifferentiableSparseFunction.
typedef GenericFunction
< EigenMatrixDense > Function
Dense function.
typedef GenericFunction
< EigenMatrixSparse > SparseFunction
Sparse function.
typedef
GenericDifferentiableFunction
< EigenMatrixDense > DifferentiableFunction
Dense differentiable function.
typedef
GenericDifferentiableFunction
< EigenMatrixSparse > DifferentiableSparseFunction
Sparse differentiable function.
typedef
GenericNumericLinearFunction
< EigenMatrixDense > NumericLinearFunction
typedef
GenericNumericQuadraticFunction
< EigenMatrixDense > NumericQuadraticFunction
typedef
GenericConstantFunction
< EigenMatrixDense > ConstantFunction
typedef
GenericIdentityFunction
< EigenMatrixDense > IdentityFunction
typedef
GenericTwiceDifferentiableFunction
< EigenMatrixDense > TwiceDifferentiableFunction
typedef
GenericTwiceDifferentiableFunction
< EigenMatrixSparse > TwiceDifferentiableSparseFunction
typedef GenericLinearFunction
< EigenMatrixDense > LinearFunction
typedef GenericLinearFunction
< EigenMatrixSparse > LinearSparseFunction
typedef
GenericQuadraticFunction
< EigenMatrixDense > QuadraticFunction
typedef
GenericQuadraticFunction
< EigenMatrixSparse > QuadraticSparseFunction
typedef TwiceDifferentiableFunction TwiceDerivableFunction
Legacy name of DifferentiableFunction.
Functions
template<typename U , typename V >
boost::shared_ptr< Chain< U, V > > chain (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Concatenate
< typename
detail::PromoteTrait< U, V >
::T_promote > > concatenate (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U >
boost::shared_ptr< Derivative
< U > > derivative (boost::shared_ptr< U > origin, typename Derivative< U >::size_type variableId=0)
template<typename U >
boost::shared_ptr< Map< U > > map (boost::shared_ptr< U > origin, typename U::size_type repeat)
template<typename U , typename V >
boost::shared_ptr< Minus< U, V > > minus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Minus< U, V > > operator- (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Plus< U, V > > plus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Plus< U, V > > operator+ (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Product< U,
V > > product (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Product< U,
V > > operator* (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U >
boost::shared_ptr< Scalar< U > > scalar (boost::shared_ptr< U > origin, typename Scalar< U >::size_type start=0, typename Scalar< U >::size_type size=1)
template<typename U >
boost::shared_ptr< Scalar< U > > operator* (typename Scalar< U >::value_type scalar, boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr< Scalar< U > > operator* (boost::shared_ptr< U > origin, typename Scalar< U >::value_type scalar)
template<typename U >
boost::shared_ptr< U > operator+ (boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr< Scalar< U > > operator- (boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr< Selection< U > > selection (boost::shared_ptr< U > origin, typename Selection< U >::size_type start=0, typename Selection< U >::size_type size=1)
template<typename P , typename C >
void addNonScalarConstraint (P &problem, boost::shared_ptr< C > constraint, std::vector< Function::interval_t > interval, std::vector< Function::value_type > scale=std::vector< Function::value_type >()) throw (std::runtime_error)
template<typename T >
std::ostream & operator<< (std::ostream &o, const BadGradient< T > &f)
Override operator<< to handle exception display.
template<typename T >
std::ostream & operator<< (std::ostream &o, const BadJacobian< T > &f)
Override operator<< to handle exception display.
template<typename T >
bool checkGradient (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::size_type functionId, const typename GenericDifferentiableFunction< T >::vector_t &x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw ()
Check if a gradient is valid.
template<typename T >
void checkGradientAndThrow (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::size_type functionId, const typename GenericDifferentiableFunction< T >::vector_t &x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw (BadGradient<T>)
template<typename T >
bool checkJacobian (const GenericDifferentiableFunction< T > &function, const typename GenericDifferentiableFunction< T >::vector_t &x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw ()
Check if a Jacobian is valid.
template<typename T >
void checkJacobianAndThrow (const GenericDifferentiableFunction< T > &function, const typename GenericDifferentiableFunction< T >::vector_t &x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw (BadJacobian<T>)
template<typename T >
std::ostream & operator<< (std::ostream &o, const GenericFunction< T > &f)
Override operator<< to handle function display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const GenericSolver &gs)
Override operator<< to handle solver display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const NoSolution &ns)
Override operator<< to display ``no solution'' objects.
ROBOPTIM_DLLAPI long int & indent (std::ostream &o)
The current indentation level for o.
ROBOPTIM_DLLAPI std::ostream & incindent (std::ostream &o)
Increment the indentation.
ROBOPTIM_DLLAPI std::ostream & decindent (std::ostream &o)
Decrement the indentation.
ROBOPTIM_DLLAPI std::ostream & resetindent (std::ostream &o)
Reset the indentation.
ROBOPTIM_DLLAPI std::ostream & iendl (std::ostream &o)
Print an end of line, then set the indentation.
ROBOPTIM_DLLAPI std::ostream & incendl (std::ostream &o)
Increment the indentation, print an end of line, and set the indentation.
ROBOPTIM_DLLAPI std::ostream & decendl (std::ostream &o)
Decrement the indentation, print an end of line, and set the indentation.
template<typename F >
std::ostream & operator<< (std::ostream &o, const ParametrizedFunction< F > &f)
Override operator<< to handle function display.
template<typename F >
std::ostream & operator<< (std::ostream &o, const Problem< F, boost::mpl::vector<> > &pb)
Override operator<< to handle problem display.
template<typename F , typename CLIST >
std::ostream & operator<< (std::ostream &o, const Problem< F, CLIST > &pb)
Override operator<< to handle problem display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const Result &r)
Override operator<< to handle result display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const SolverError &e)
Override operator<< to handle error display.
template<typename T >
T * unionCast (void *ptr)
const std::string demangle (const char *name)
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const Parameter &parameter)
Override operator<< to display ``parameters'' objects.
template<typename T >
std::ostream & operator<< (std::ostream &, const std::vector< T > &)
Display a vector.
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &, const std::pair< T1, T2 > &)
Display a pair.
template<typename T >
std::ostream & operator<< (std::ostream &, const Eigen::MatrixBase< T > &)
Display an Eigen object with the appropriate IOFormat.
ROBOPTIM_DLLAPI
GenericFunctionTraits
< EigenMatrixDense >::matrix_t sparse_to_dense (const GenericFunctionTraits< EigenMatrixSparse >::matrix_t &)
Convert a sparse matrix into a dense matrix.
ROBOPTIM_DLLAPI
GenericFunctionTraits
< EigenMatrixDense >::vector_t sparse_to_dense (const GenericFunctionTraits< EigenMatrixSparse >::gradient_t &v)
Convert a sparse vector into a dense vector.
template<typename DerivedA , typename DerivedB >
bool allclose (const Eigen::DenseBase< DerivedA > &a, const Eigen::DenseBase< DerivedB > &b, const typename DerivedA::RealScalar &rtol=Eigen::NumTraits< typename DerivedA::RealScalar >::dummy_precision(), const typename DerivedA::RealScalar &atol=Eigen::NumTraits< typename DerivedA::RealScalar >::epsilon())
Compare dense vectors (matrices) using both relative and absolute tolerances.
template<typename DerivedA , typename DerivedB >
bool allclose (const Eigen::SparseMatrixBase< DerivedA > &a, const Eigen::SparseMatrixBase< DerivedB > &b, const typename DerivedA::RealScalar &rtol=Eigen::NumTraits< typename DerivedA::RealScalar >::dummy_precision(), const typename DerivedA::RealScalar &atol=Eigen::NumTraits< typename DerivedA::RealScalar >::epsilon())
Compare sparse vectors (matrices) using both relative and absolute tolerances.
Variables
static const double finiteDifferenceThreshold = 1e-4
Default threshold for checkGradient.
static const double finiteDifferenceEpsilon = 1e-8
Default epsilon for finite difference class.
Detailed Description
Meta-functions, functions and solvers related classes.
Typedef Documentation
typedef GenericConstantFunction<EigenMatrixDense> roboptim::ConstantFunction
typedef DifferentiableFunction roboptim::DerivableFunction
Legacy name of TwiceDifferentiableFunction.
typedef DifferentiableSparseFunction roboptim::DerivableSparseFunction
Legacy name of TwiceDifferentiableSparseFunction.
typedef GenericDifferentiableFunction<EigenMatrixDense> roboptim::DifferentiableFunction
Dense differentiable function.
Examples:
problem-cc.cc.
typedef GenericDifferentiableFunction<EigenMatrixSparse> roboptim::DifferentiableSparseFunction
Sparse differentiable function.
typedef GenericFunction<EigenMatrixDense> roboptim::Function
Dense function.
Examples:
visualization-gnuplot-function.cc.
typedef GenericIdentityFunction<EigenMatrixDense> roboptim::IdentityFunction
typedef GenericLinearFunction<EigenMatrixDense> roboptim::LinearFunction
typedef GenericLinearFunction<EigenMatrixSparse> roboptim::LinearSparseFunction
typedef GenericNumericLinearFunction<EigenMatrixDense> roboptim::NumericLinearFunction
typedef GenericNumericQuadraticFunction<EigenMatrixDense> roboptim::NumericQuadraticFunction
typedef GenericQuadraticFunction<EigenMatrixDense> roboptim::QuadraticFunction
typedef GenericQuadraticFunction<EigenMatrixSparse> roboptim::QuadraticSparseFunction
typedef GenericFunction<EigenMatrixSparse> roboptim::SparseFunction
Sparse function.
typedef TwiceDifferentiableFunction roboptim::TwiceDerivableFunction
Legacy name of DifferentiableFunction.
typedef GenericTwiceDifferentiableFunction<EigenMatrixDense> roboptim::TwiceDifferentiableFunction
typedef GenericTwiceDifferentiableFunction<EigenMatrixSparse> roboptim::TwiceDifferentiableSparseFunction
Function Documentation
template<typename DerivedA , typename DerivedB > bool roboptim::allclose (const Eigen::DenseBase< DerivedA > & a, const Eigen::DenseBase< DerivedB > & b, const typename DerivedA::RealScalar & rtol = Eigen::NumTraits<typename DerivedA::RealScalar>::dummy_precision(), const typename DerivedA::RealScalar & atol = Eigen::NumTraits<typename DerivedA::RealScalar>::epsilon())
Compare dense vectors (matrices) using both relative and absolute tolerances.
See also:
http://stackoverflow.com/a/15052131/1043187
Examples:
numeric-quadratic-function.cc.
Referenced by checkGradient(), and checkJacobian().
template<typename DerivedA , typename DerivedB > bool roboptim::allclose (const Eigen::SparseMatrixBase< DerivedA > & a, const Eigen::SparseMatrixBase< DerivedB > & b, const typename DerivedA::RealScalar & rtol = Eigen::NumTraits<typename DerivedA::RealScalar>::dummy_precision(), const typename DerivedA::RealScalar & atol = Eigen::NumTraits<typename DerivedA::RealScalar>::epsilon())
Compare sparse vectors (matrices) using both relative and absolute tolerances.
See also:
http://stackoverflow.com/a/15052131/1043187
template<typename U , typename V > boost::shared_ptr<Chain<U, V> > roboptim::chain (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Chain< U, V >::left(), and roboptim::Chain< U, V >::right().
template<typename U , typename V > boost::shared_ptr<Concatenate<typename detail::PromoteTrait<U, V>::T_promote > > roboptim::concatenate (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Concatenate< U >::left(), and roboptim::Concatenate< U >::right().
std::ostream & roboptim::decendl (std::ostream & o)
Decrement the indentation, print an end of line, and set the indentation.
References decindent(), and iendl().
std::ostream & roboptim::decindent (std::ostream & o)
Decrement the indentation.
References indent().
Referenced by decendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::OptimizationLogger< T >::perIterationCallbackUnsafe(), roboptim::BadGradient< T >::print(), roboptim::GenericNumericLinearFunction< T >::print(), roboptim::GenericIdentityFunction< T >::print(), roboptim::GenericConstantFunction< T >::print(), roboptim::Result::print(), roboptim::GenericNumericQuadraticFunction< T >::print(), roboptim::ResultWithWarnings::print(), roboptim::BadJacobian< T >::print(), roboptim::Solver< F, C >::print(), roboptim::Problem< F, boost::mpl::vector<> >::print(), and roboptim::Problem< F, CLIST >::print().
const std::string roboptim::demangle (const char * name) [inline]
Referenced by roboptim::SolverFactory< T >::SolverFactory().
template<typename U > boost::shared_ptr<Derivative<U> > roboptim::derivative (boost::shared_ptr< U > origin, typename Derivative< U >::size_type variableId = 0)
Referenced by roboptim::NTimesDerivableFunction< 2 >::derivative(), roboptim::Split< T >::impl_derivative(), roboptim::CachedFunction< T >::impl_derivative(), roboptim::NTimesDerivableFunction< 2 >::impl_gradient(), roboptim::NTimesDerivableFunction< 2 >::impl_hessian(), and roboptim::NTimesDerivableFunction< 2 >::isValidDerivative().
std::ostream & roboptim::iendl (std::ostream & o)
Print an end of line, then set the indentation.
References indent().
Referenced by decendl(), incendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::OptimizationLogger< T >::OptimizationLogger(), roboptim::OptimizationLogger< T >::perIterationCallbackUnsafe(), roboptim::BadGradient< T >::print(), roboptim::GenericNumericLinearFunction< T >::print(), roboptim::GenericIdentityFunction< T >::print(), roboptim::Result::print(), roboptim::GenericConstantFunction< T >::print(), roboptim::GenericNumericQuadraticFunction< T >::print(), roboptim::ResultWithWarnings::print(), roboptim::BadJacobian< T >::print(), roboptim::Solver< F, C >::print(), roboptim::Problem< F, boost::mpl::vector<> >::print(), roboptim::Problem< F, CLIST >::print(), and roboptim::OptimizationLogger< T >::~OptimizationLogger().
std::ostream & roboptim::incendl (std::ostream & o)
Increment the indentation, print an end of line, and set the indentation.
References iendl(), and incindent().
Referenced by roboptim::Problem< F, boost::mpl::vector<> >::print(), and roboptim::Problem< F, CLIST >::print().
std::ostream & roboptim::incindent (std::ostream & o)
Increment the indentation.
References indent().
Referenced by incendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::OptimizationLogger< T >::perIterationCallbackUnsafe(), roboptim::BadGradient< T >::print(), roboptim::GenericNumericLinearFunction< T >::print(), roboptim::GenericIdentityFunction< T >::print(), roboptim::GenericConstantFunction< T >::print(), roboptim::Result::print(), roboptim::GenericNumericQuadraticFunction< T >::print(), roboptim::ResultWithWarnings::print(), roboptim::BadJacobian< T >::print(), and roboptim::Solver< F, C >::print().
long int & roboptim::indent (std::ostream & o)
The current indentation level for o.
Referenced by decindent(), iendl(), incindent(), roboptim::GenericTwiceDifferentiableFunction< T >::print(), roboptim::GenericDifferentiableFunction< T >::print(), roboptim::GenericFunction< T >::print(), and resetindent().
template<typename U > boost::shared_ptr<Map<U> > roboptim::map (boost::shared_ptr< U > origin, typename U::size_type repeat)
References roboptim::Map< U >::origin().
template<typename U , typename V > boost::shared_ptr<Minus<U, V> > roboptim::minus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Minus< U, V >::left(), and roboptim::Minus< U, V >::right().
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator* (typename Scalar< U >::value_type scalar, boost::shared_ptr< U > origin)
References roboptim::Scalar< U >::origin(), and scalar().
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator* (boost::shared_ptr< U > origin, typename Scalar< U >::value_type scalar)
References roboptim::Scalar< U >::origin(), and scalar().
template<typename U , typename V > boost::shared_ptr<Product<U, V> > roboptim::operator* (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Product< U, V >::left(), and roboptim::Product< U, V >::right().
template<typename U , typename V > boost::shared_ptr<Plus<U, V> > roboptim::operator+ (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Plus< U, V >::left(), and roboptim::Plus< U, V >::right().
template<typename U > boost::shared_ptr<U> roboptim::operator+ (boost::shared_ptr< U > origin)
References roboptim::Scalar< U >::origin().
template<typename U , typename V > boost::shared_ptr<Minus<U, V> > roboptim::operator- (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Minus< U, V >::left(), and roboptim::Minus< U, V >::right().
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator- (boost::shared_ptr< U > origin)
References roboptim::Scalar< U >::origin().
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const std::vector< T > & vect)
Display a vector.
template<typename T1 , typename T2 > std::ostream & roboptim::operator<< (std::ostream & o, const std::pair< T1, T2 > & p)
Display a pair.
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const Eigen::MatrixBase< T > & matrix)
Display an Eigen object with the appropriate IOFormat.
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const BadGradient< T > & f)
Override operator<< to handle exception display.
Parameters:
o output stream used for display
f function to be displayed
Returns:
output stream
std::ostream & roboptim::operator<< (std::ostream & o, const Result & r)
Override operator<< to handle result display.
Parameters:
o output stream used for display
r result to be displayed
Returns:
output stream
References roboptim::Result::print().
std::ostream & roboptim::operator<< (std::ostream & o, const SolverError & e)
Override operator<< to handle error display.
Parameters:
o output stream used for display
e error to be displayed
Returns:
output stream
References roboptim::SolverError::print().
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const BadJacobian< T > & f)
Override operator<< to handle exception display.
Parameters:
o output stream used for display
f function to be displayed
Returns:
output stream
template<typename F > std::ostream & roboptim::operator<< (std::ostream & o, const ParametrizedFunction< F > & f)
Override operator<< to handle function display.
Parameters:
o output stream used for display
f function to be displayed
Returns:
output stream
std::ostream & roboptim::operator<< (std::ostream & o, const GenericSolver & gs)
Override operator<< to handle solver display.
Parameters:
o output stream used for display
gs solver to be displayed
Returns:
output stream
References roboptim::GenericSolver::print().
std::ostream & roboptim::operator<< (std::ostream & o, const NoSolution & ns)
Override operator<< to display ``no solution'' objects.
Parameters:
o output stream used for display
ns NoSolution object, ignored
Returns:
output stream
template<typename U , typename V > boost::shared_ptr<Plus<U, V> > roboptim::plus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Plus< U, V >::left(), and roboptim::Plus< U, V >::right().
template<typename U , typename V > boost::shared_ptr<Product<U, V> > roboptim::product (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
References roboptim::Product< U, V >::left(), and roboptim::Product< U, V >::right().
std::ostream & roboptim::resetindent (std::ostream & o)
Reset the indentation.
References indent().
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::scalar (boost::shared_ptr< U > origin, typename Scalar< U >::size_type start = 0, typename Scalar< U >::size_type size = 1)
References roboptim::Scalar< U >::origin().
Referenced by operator*().
template<typename U > boost::shared_ptr<Selection<U> > roboptim::selection (boost::shared_ptr< U > origin, typename Selection< U >::size_type start = 0, typename Selection< U >::size_type size = 1)
References roboptim::Selection< U >::origin().
GenericFunctionTraits< EigenMatrixDense >::matrix_t roboptim::sparse_to_dense (const GenericFunctionTraits< EigenMatrixSparse >::matrix_t & m)
Convert a sparse matrix into a dense matrix.
Examples:
finite-difference-gradient.cc.
GenericFunctionTraits< EigenMatrixDense >::vector_t roboptim::sparse_to_dense (const GenericFunctionTraits< EigenMatrixSparse >::gradient_t & v)
Convert a sparse vector into a dense vector.
template<typename T > T* roboptim::unionCast (void * ptr)
Variable Documentation
const double roboptim::finiteDifferenceEpsilon = 1e-8 [static]
Default epsilon for finite difference class.
const double roboptim::finiteDifferenceThreshold = 1e-4 [static]
Default threshold for checkGradient.