roboptim::visualization::gnuplot::detail Namespace Reference
roboptim::visualization::gnuplot::detail Namespace Reference
Functions
std::string dense_jacobian_to_gnuplot (const DifferentiableFunction::jacobian_t &jac, const std::string &name)
std::string sparse_jacobian_to_gnuplot (const DifferentiableSparseFunction::jacobian_t &jac, const std::string &name)
template<typename T >
void set_matrix_header (std::string &str, const typename GenericFunctionTraits< T >::matrix_t &mat)
std::string dense_matrix_to_gnuplot (const GenericFunctionTraits< EigenMatrixDense >::matrix_t &mat)
std::string sparse_matrix_to_gnuplot (const GenericFunctionTraits< EigenMatrixSparse >::matrix_t &mat)
Function Documentation
std::string roboptim::visualization::gnuplot::detail::dense_jacobian_to_gnuplot (const DifferentiableFunction::jacobian_t & jac, const std::string & name)
References roboptim::visualization::gnuplot::Command::command(), and roboptim::visualization::gnuplot::plot_mat().
Referenced by roboptim::visualization::gnuplot::plot_jac().
std::string roboptim::visualization::gnuplot::detail::dense_matrix_to_gnuplot (const GenericFunctionTraits< EigenMatrixDense >::matrix_t & mat)
References roboptim::visualization::normalize().
Referenced by roboptim::visualization::gnuplot::plot_mat().
template<typename T > void roboptim::visualization::gnuplot::detail::set_matrix_header (std::string & str, const typename GenericFunctionTraits< T >::matrix_t & mat)
std::string roboptim::visualization::gnuplot::detail::sparse_jacobian_to_gnuplot (const DifferentiableSparseFunction::jacobian_t & jac, const std::string & name)
References roboptim::visualization::gnuplot::Command::command(), and roboptim::visualization::gnuplot::plot_mat().
Referenced by roboptim::visualization::gnuplot::plot_jac().
std::string roboptim::visualization::gnuplot::detail::sparse_matrix_to_gnuplot (const GenericFunctionTraits< EigenMatrixSparse >::matrix_t & mat)
Referenced by roboptim::visualization::gnuplot::plot_mat().