#!/bin/sh
set -ev

if [ -d debian ]; then
    ; # FIXME: upload the generated Debian source package to Launchpad
    ; # for publication.
else
    coveralls						\
	-e _travis/install				\
	-e _travis/build/eigen-eigen-ffa86ffb5570/	\
	-e tests
    git remote set-url origin \
	https://thomas-moulard:${GH_TOKEN}@github.com/roboptim/roboptim-core.git
    git fetch origin gh-pages:gh-pages
    cd _travis/build/doc && ../../../cmake/github/update-doxygen-doc.sh
fi
