#!/bin/sh
set -ev

# Retrive the submodules.
git submodule update --init --recursive

# Update the apt local cache.
sudo apt-get update -qq

# Check if we are in a debian branch...
if [ -d debian ]; then
    # If we are, we install Debian package development tools and
    # create a sid pbuilder. Package dependencies will be installed
    # automatically.
    sudo apt-get install -qq			\
	debootstrap devscripts			\
	git-buildpackage debian-archive-keyring

    # Remove previous sandbox.
    sudo rm -rf /var/cache/pbuilder/base-unstable.cow
    # Create a new one.
    DIST=unstable git-pbuilder create		\
	--debootstrapopts "--variant=buildd"	\
	--debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg" \
	--mirror http://ftp.us.debian.org/debian/
else
    # ...otherwise we install the dependencies explicitly.
    sudo apt-get install -qq			\
	doxygen doxygen-latex			\
	libltdl-dev libboost-all-dev		\
	liblog4cxx10-dev libeigen3-dev
    sudo pip install cpp-coveralls --use-mirrors
fi
